// Code generated by goctl. DO NOT EDIT.
// Source: grpc_user_domain.proto

package server

import (
	"context"

	"github.com/wuyazi/grpc_user_domain/internal/logic"
	"github.com/wuyazi/grpc_user_domain/internal/svc"
	"github.com/wuyazi/grpc_user_domain/user_domain"
)

type UserCommendServer struct {
	svcCtx *svc.ServiceContext
	user_domain.UnimplementedUserCommendServer
}

func NewUserCommendServer(svcCtx *svc.ServiceContext) *UserCommendServer {
	return &UserCommendServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCommendServer) Create(ctx context.Context, in *user_domain.CreateReq) (*user_domain.UserIdResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *UserCommendServer) UpdateNickname(ctx context.Context, in *user_domain.UpdateNicknameReq) (*user_domain.UserIdResp, error) {
	l := logic.NewUpdateNicknameLogic(ctx, s.svcCtx)
	return l.UpdateNickname(in)
}

func (s *UserCommendServer) UpdateAge(ctx context.Context, in *user_domain.UpdateAgeReq) (*user_domain.UserIdResp, error) {
	l := logic.NewUpdateAgeLogic(ctx, s.svcCtx)
	return l.UpdateAge(in)
}

func (s *UserCommendServer) UpdateGender(ctx context.Context, in *user_domain.UpdateGenderReq) (*user_domain.UserIdResp, error) {
	l := logic.NewUpdateGenderLogic(ctx, s.svcCtx)
	return l.UpdateGender(in)
}
